version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
  mysql:
    build: ./mysql
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: reservation_form
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/etc/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

volumes:
  mysql_data: